# Generated by Django 5.0.1 on 2024-04-25 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_keyword_product_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='value',
        ),
    ]
